---
- hosts: localhost ansible_connection=local
  roles:
    - { role: basics, tags: ["basics"] }
    - { role: aesthetics, tags: ["aesthetics"] }
    - { role: brews, tags: ["homebrew"] }
    - { role: casks, tags: ["homebrew","caskroom"] }
    - { role: ruby, tags: ["ruby"] }
    - { role: emacs, tags: ["emacs"] }
    - { role: gstreamer, tags: ["gstreamer", "homebrew"] }
