---
- name: Bootstrapping macOS
  hosts: localhost
  connection: local
  roles:
    - { role: basics, tags: ["basics"] }
    - { role: appstore, tags: ["appstore","mas"] }
    - { role: aesthetics, tags: ["aesthetics"] }
    - { role: brews, tags: ["homebrew"] }
    - { role: casks, tags: ["homebrew","caskroom"] }
    - { role: ruby, tags: ["ruby"] }
    - { role: node, tags: ["node","javascript"] }
    - { role: emacs, tags: ["emacs"] }
    - { role: gstreamer, tags: ["gstreamer", "homebrew"] }
