#!/bin/bash

# This script is going to set up a mac just the way I like it.
# I use bash.

if ! xcode-select -p > /dev/null 2>&1; then
  xcode-select --install
fi

if [ ! `command -v pip` ]; then
  sudo easy_install pip
fi

if [ ! `command -v ansible-playbook` ]; then
  sudo pip install ansible
fi

# ansible-playbook local/local.yml
