---
- name: Node.js installation
  homebrew: name=node state=present
- name: Yarn package management installation
  homebrew: name=yarn state=present
- name: node-gyp global installation
  npm:
    name: node-gyp
    global: yes
    state: present
