---
- name: rbenv (Ruby) installation
  homebrew: name=rbenv state=present
- name: rbenv-default-gems installation
  homebrew: name=rbenv-default-gems state=present
- name: Ruby {{ ruby_version }} installation
  shell: rbenv install {{ ruby_version }} creates=~/.rbenv/versions/{{ ruby_version }}
  notify: set global ruby
