---
- name: Homebrew installation
  ansible.builtin.shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  args:
    creates: /opt/homebrew
  tags:
    - homebrew
- name: Mac App Store CLI installation
  community.general.homebrew: name=mas state=present
  tags:
    - homebrew
    - mas
- name: Git installation
  community.general.homebrew: name=git state=present
  tags:
    - homebrew
    - git
- name: GNU Stow installation
  community.general.homebrew: name=stow state=present
  tags:
    - homebrew
    - dotfiles
- name: dotfiles download
  ansible.builtin.git: repo=git@github.com:mwunsch/dotfiles.git dest=~/dotfiles accept_hostkey=yes
  tags:
    - dotfiles
    - git
- name: dotfiles unpack
  ansible.builtin.command: /usr/local/bin/stow home chdir=~/dotfiles creates=~/.bash_profile
  tags:
    - dotfiles
