---
- hosts: all
  remote_user: freebsd
  gather_facts: no
  become: true
  tasks:
    - name: install python
      raw: env ASSUME_ALWAYS_YES=YES pkg install python
      register: py_install
      changed_when: py_install.stdout_lines | last != "The most recent version of packages are already installed"

- hosts: all
  remote_user: freebsd
  become: true
  tasks:
    - name: install bash
      pkgng: name=bash state=present
    - name: mount fdesc
      # we ensure fdescfs(5) is mounted for bash process substitution
      mount: src=fdesc name=/dev/fd fstype=fdescfs opts=rw state=mounted
    - name: install git
      pkgng: name=git state=present
    - name: install stow
      pkgng: name=stow state=present
    - name: add mw user
      user: name=mw groups=wheel shell=/usr/local/bin/bash append=yes
