---
- hosts: all
  remote_user: freebsd
  gather_facts: no
  become: true
  tasks:
    - name: install python
      raw: pkg info -e python || env ASSUME_ALWAYS_YES=YES pkg install python
      register: result
      changed_when: result.stdout != ""

- hosts: all
  remote_user: freebsd
  become: true
  tasks:
    - name: install bash
      pkgng: name=bash state=present
    - name: mount fdesc
      # we ensure fdescfs(5) is mounted for bash process substitution
      mount: src=fdesc name=/dev/fd fstype=fdescfs opts=rw state=mounted
    - name: set timezone
      # Ansible 2.3 supports BSD with the timezone module
      command: /usr/sbin/tzsetup -s America/New_York creates=/etc/localtime
    # setting up ntpd. alternative is to use sysrc command
    - name: enable ntpd
      lineinfile:
        name: /etc/rc.conf
        line: 'ntpd_enabled="YES"'
        regexp: '^ntpd_enabled='
      notify:
        - restart ntpd
    - name: sync ntpd on start
      lineinfile:
        name: /etc/rc.conf
        line: 'ntpd_sync_on_start="YES"'
        regexp: '^ntpd_sync_on_start='
    - name: ntpd running
      service: name=ntpd state=started enabled=yes
    - name: install git
      pkgng: name=git state=present
    - name: install stow
      pkgng: name=stow state=present
    - name: install hub
      pkgng: name=hub state=present
    - name: install rbenv
      pkgng: name=rbenv state=present
    - name: install screen
      pkgng: name=screen state=present
    - name: install emacs
      pkgng: name=emacs-nox11 state=present
    - name: install wget
      pkgng: name=wget state=present
    - name: copy git prompt into place
      command: /bin/cp /usr/local/share/git-core/contrib/completion/git-prompt.sh /usr/local/etc/bash_completion.d/
      args:
        creates: /usr/local/etc/bash_completion.d/git-prompt.sh
    - name: copy git completions into place
      command: /bin/cp /usr/local/share/git-core/contrib/completion/git-completion.bash /usr/local/etc/bash_completion.d/
      args:
        creates: /usr/local/etc/bash_completion.d/git-completion.bash
    - name: add mw user
      user: name=mw groups=wheel shell=/usr/local/bin/bash append=yes
    - name: add authorized keys from github
      authorized_key: user=mw key=https://github.com/mwunsch.keys
    - name: install OpenJDK 8
      pkgng: name=openjdk8 state=present
    - name: install leiningen
      pkgng: name=leiningen state=present
  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted

- hosts: all
  remote_user: mw
  tasks:
    - name: get dotfiles
      # Make sure you're using agent forwarding!
      git: repo=git@github.com:mwunsch/dotfiles.git dest=~/dotfiles accept_hostkey=yes
    - name: unpack dotfiles
      command: /usr/local/bin/stow home chdir=~/dotfiles creates=~/.bash_profile
    - name: get emacs.d
      git: repo=git@github.com:mwunsch/emacs.d.git dest=~/.emacs.d accept_hostkey=yes
    - name: install ruby-build
      git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build
    - name: install ruby 2.3.3
      # make a cup of coffee
      shell: rbenv install 2.3.3 creates=~/.rbenv/versions/2.3.3
    - name: set ruby 2.3.3 as global ruby
      lineinfile:
        name: ~/.rbenv/version
        line: '2.3.3'
        create: yes
