---
- name: install git
  pkgng: name=git state=present
- name: copy git prompt into place
  command: /bin/cp /usr/local/share/git-core/contrib/completion/git-prompt.sh /usr/local/etc/bash_completion.d/
  args:
    creates: /usr/local/etc/bash_completion.d/git-prompt.sh
- name: copy git completions into place
  command: /bin/cp /usr/local/share/git-core/contrib/completion/git-completion.bash /usr/local/etc/bash_completion.d/
  args:
    creates: /usr/local/etc/bash_completion.d/git-completion.bash
- name: install utilities
  pkgng: name={{ item }} state=present
  with_items:
    - stow
    - tree
    - hub
    - tmux
    - emacs-nox11
    - aspell
    - en-aspell
    - wget
    - pkgconf
- name: install language tooling
  pkgng: name={{ item }} state=present
  with_items:
    - openjdk8
    - leiningen
    - rbenv
    - racket-minimal
    - node
    - npm
