---
- name: VirtualBox installation
  homebrew_cask: name=virtualbox state=present
  tags:
    - virtualization
- name: Docker installation
  homebrew_cask: name=docker state=present
  tags:
    - docker
- name: Vagrant installation
  tags:
    - virtualization
  homebrew_cask: name=vagrant state=present
- name: LICEcap installation
  homebrew_cask: name=licecap state=present
- name: MacTeX installation
  homebrew_cask: name=mactex state=present
# alternatively:
# - name: BasicTeX installation
#   homebrew_Cask: name=basictex state=present
- name: Racket installation
  homebrew_cask: name=racket state=present
  tags:
    - racket
