---
- hosts: freebsd
  remote_user: freebsd
  gather_facts: no
  become: true
  tasks:
    - name: install python
      raw: pkg info -e python || env ASSUME_ALWAYS_YES=YES pkg install python
      register: result
      changed_when: result.stdout != ""

- hosts: freebsd
  remote_user: freebsd
  become: true
  roles:
    - bootstrap
    - packages
    - user

- hosts: freebsd
  remote_user: mw
  tasks:
    - name: get dotfiles
      # Make sure you're using agent forwarding!
      git: repo=git@github.com:mwunsch/dotfiles.git dest=~/dotfiles accept_hostkey=yes
    - name: unpack dotfiles
      command: /usr/local/bin/stow home chdir=~/dotfiles creates=~/.bash_profile
    - name: get emacs.d
      git: repo=git@github.com:mwunsch/emacs.d.git dest=~/.emacs.d accept_hostkey=yes
    - name: install ruby-build
      git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build
    - name: install ruby 2.5.1
      # make a cup of coffee
      shell: rbenv install 2.5.1 creates=~/.rbenv/versions/2.5.1
    - name: set ruby 2.5.1 as global ruby
      lineinfile:
        name: ~/.rbenv/version
        line: '2.5.1'
        create: yes

- hosts: freebsd
  remote_user: mw
  name: Setting up Plex
  roles:
    - { role: plex, tags: ["plex"] }
