---
- name: jq installation
  homebrew: name=jq state=present
- name: tree installation
  homebrew: name=tree state=present
- name: ack installation
  homebrew: name=ack state=present
- name: SETEC ASTRONOMY
  homebrew: name=no-more-secrets state=present
- name: Leiningen (Clojure) installation
  homebrew: name=leiningen state=present
  tags:
    - clojure
- name: csvkit installation
  homebrew: name=csvkit state=present
- name: youtube-dl installation
  homebrew: name=youtube-dl state=present
- name: pandoc installation
  homebrew: name=pandoc state=present
- name: ffmpeg installation
  homebrew: name=ffmpeg state=present
- name: figlet installation
  homebrew: name=figlet state=present
- name: imagemagick installation
  homebrew: name=imagemagick state=present
- name: golang installation
  homebrew: name=go state=present
  notify: make gopath directory
  tags:
    - golang
- name: elixir installation
  homebrew: name=elixir state=present
  tags:
    - elixir
    - erlang
