---
# SF Mono is a good font. Copy it from Terminal.app and install it system-wide:
# - https://simonfredsted.com/1438
- name: SF Mono font availability
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts/
  with_fileglob:
    - "/Applications/Utilities/Terminal.app/Contents/Resources/Fonts/SFMono*.otf"
  tags:
    - font
# Map Caps Lock to Control as God Intended.
# First, get the right values for the keyboard identifier out of ioreg:
- name: Apple Internal Keyboard vendor/product id
  shell: |
    set -e
    tmpfile=$(mktemp)
    ioreg -c AppleHSSPIDevice -r -d 1 -a > $tmpfile
    vendor_id=$(/usr/libexec/PlistBuddy -c 'Print :0:idVendor' $tmpfile)
    product_id=$(/usr/libexec/PlistBuddy -c 'Print :0:idProduct' $tmpfile)
    echo $vendor_id-$product_id-0
  register: keyboard_id
  changed_when: false
  check_mode: no
  ignore_errors: true
  tags:
    - keyboard
# Then, perform the mapping with `defaults` as described in:
# https://developer.apple.com/library/content/technotes/tn2450/_index.html
# Preferences are cached; it will take a moment (or a login/logout) to take effect.
- name: Caps-Lock -> Ctrl mapping
  shell: |
    set -e
    key='com.apple.keyboard.modifiermapping.{{ keyboard_id.stdout }}'
    found=$(defaults -currentHost find $key)
    if [[ $found =~ ^Found ]]; then
      echo $found
      exit 0
    else
      defaults -currentHost write -globalDomain $key -array \
      '<dict><key>HIDKeyboardModifierMappingDst</key><integer>30064771300</integer><key>HIDKeyboardModifierMappingSrc</key><integer>30064771129</integer></dict>'
    fi
  register: result
  changed_when: result.stdout == ''
  when: keyboard_id.rc == 0
  tags:
    - keyboard
# Saturn terminal theme is nice:
# https://github.com/psql/saturn-colors
- name: Saturn Terminal.app theme installation
  shell: |
    set -e
    terminal_theme=$(defaults read com.apple.Terminal 'Default Window Settings')
    if [[ $terminal_theme = 'saturn' ]] ; then
      echo "Default Terminal theme already set: $terminal_theme"
      exit 0
    else
      open {{ item }}
      defaults write com.apple.Terminal 'Default Window Settings' -string 'saturn'
      defaults write com.apple.Terminal 'Startup Window Settings' -string 'saturn'
    fi
  with_first_found:
    - 'saturn.terminal'
  register: result
  changed_when: result.stdout == ''
  tags:
    - terminal
