---
- name: tap Mitsuharu Yamamoto Emacs-Mac port
  homebrew_tap: name=railwaycat/emacsmacport state=present
- name: Emacs-Mac installation
  homebrew_cask: name=emacs-mac state=present
- name: emacs.d setup
  git: repo=git@github.com:mwunsch/emacs.d.git dest=~/.emacs.d accept_hostkey=yes
